### ISSUE TITLE
In url.json path and query operations should not have parameters be constants

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest.testserver#93]
Currently most of them are lowered to strings by the modeler so we don't actually test anything. Headers swagger is done better from this perspective.

**Comment by lmazuel** [comment]
Why not? I understand response as constant is a problem, but I don't see why parameters as constant is.

**Comment by pakrym** [comment]
Because modeler already gives us a correctly preformatted string, we are not verifying that generated code knows how to send a parameter with the right format.


For example this is C# generated code:
```
        public static async ValueTask<Response> GetBooleanFalseAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, string host = "http://localhost:3000", CancellationToken cancellationToken = default)
        {
            using var scope = clientDiagnostics.CreateScope("url.GetBooleanFalse");
            scope.Start();
            try
            {
                var request = pipeline.CreateRequest();
                request.Method = RequestMethod.Get;
                request.Uri.Reset(new Uri($"{host}"));
                request.Uri.AppendPath("/queries/bool/false", false);
                request.Uri.AppendQuery("boolQuery", "false", true);
                var response = await pipeline.SendRequestAsync(request, cancellationToken).ConfigureAwait(false);
                cancellationToken.ThrowIfCancellationRequested();
                return response;
            }
            catch (Exception e)
            {
                scope.Failed(e);
                throw;
            }
        }
```

Note how `"boolQuery", "false",` has false as a constant. If it was a parameter this tests would've caught that we are formatting bools as `False`.

**Comment by lmazuel** [comment]
Got not problem to generate it in Python :|
```python
    def get_boolean_false(self, cls=None, **kwargs):
        error_map = kwargs.pop('error_map', None)
        bool_query = False

        # Construct URL
        url = self.get_boolean_false.metadata['url']

        # Construct parameters
        query_parameters = {}
        query_parameters['boolQuery'] = self._serialize.query("bool_query", bool_query, 'bool')
```

The modeler is giving you the right thing:
The constant:
```yaml
  - &ref_48
    type: constant
    value:
      value: false
      language:
        default:
          name: ''
          description: ''
    valueType: *ref_0
    language:
      default:
        name: Constant17
        description: MISSING·SCHEMA-DESCRIPTION-CHOICE
    protocol: {}
```
The valueType:
```yaml
  booleans:
  - &ref_0
    type: boolean
    language:
      default:
        name: bool
        description: simple boolean
    protocol: {}
```

It's explicitly a constant of type boolean, I don't see the trouble here?

**Comment by lmazuel** [comment]
So when you say "modeler already gives us a correctly preformatted string," that's actually not true, the modeler is gving you the actual boolean type "false", not the string "false"

**Comment by pakrym** [comment]
I see, so passing tests is just an artifact of our deserializer that always reads constant values as strings and all string representations matching what test server expects.

In theory having values be parameters would've caught it but not sure if it's fair to claim that this is a problem with swagger.

**Comment by lmazuel** [comment]
There is constant as input in Swagger right now for sure (check name availability requires a type that is always the same string, don't ask me why they did it like that....), so supporting all kind of possible type of input constant seems important to me.

I'd close as "by design" if you're fine with it :)

**Comment by pakrym** [comment]
Yep, agreed.

**Comment by pakrym** [comment]
Datetime/date parameters seem to be string though.
```
  - !<!ConstantSchema> &ref_40
    type: constant
    value: !<!ConstantValue> 
      value: '2012-01-01'
      language:
        default:
          name: ''
          description: ''
    valueType: *ref_1
    language: !<!Languages> 
      default:
        name: Constant14
        description: MISSING·SCHEMA-DESCRIPTION-CHOICE
    protocol: !<!Protocols> {}
  - !<!ConstantSchema> &ref_42
    type: constant
    value: !<!ConstantValue> 
      value: '2012-01-01T01:01:01Z'
      language:
        default:
          name: ''
          description: ''
    valueType: *ref_1
    language: !<!Languages> 
      default:
        name: Constant15
        description: MISSING·SCHEMA-DESCRIPTION-CHOICE
    protocol: !<!Protocols> {}
```

```
choiceType: !<!StringSchema> &ref_1
      type: string
      language: !<!Languages> 
        default:
          name: string
          description: simple string
```
